version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: medprice_db
    ports:
      - "5433:5432"  # Внешний порт меняем на 5433, чтобы не пересекаться с локальным Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: